

######## SIMPLE WORKER #########
worker:
  build: base_docker
  command: {{WORKER_COMMAND}}
  volumes:
   - ./generic_worker:/generic_worker 
  working_dir: {{WORKER_WORKING_DIR}}
  environment:
   - PYTHONUNBUFFERED=TRUE
   - AWS_ACCESS_ID
   - AWS_ACCESS_KEY_ID
   - AWS_SECRET_ACCESS_KEY
   - ACTIVE_MASTER
   - THEANO_FLAGS='floatX=float32'
   - OMP_NUM_THREADS
   - JOBLIB_TEMP_FOLDER=/tmp
####################################
