

######## SIMPLE WORKER #########
worker:
  build: base_docker
  command: {{WORKER_COMMAND}}
  volumes:
   - ./generic_worker:/generic_worker 
  working_dir: {{WORKER_WORKING_DIR}}
  environment:
   - PYTHONUNBUFFERED=TRUE
   - AWS_ACCESS_ID
   - AWS_SECRET_ACCESS_KEY
   - ACTIVE_MASTER
   - THEANO_FLAGS='floatX=float32'
####################################



# ######## MASTER MACHINE #########
# masterapi:
#   build: base_docker
#   command: gunicorn  -k gevent  --reload -b 0.0.0.0:8000 -w 5 master_api:app
#   volumes:
#     - master_api:/master_api
#   working_dir: /master_api
#   ports:
#     - "0.0.0.0:8000:8000" # gunicorn
#   links:
#     - masterredis:MASTERREDIS
#   environment:
#    - PYTHONUNBUFFERED=TRUE

# masterredis:
#   image: redis
#   command: redis-server
#   volumes:
#    - masterapi
# ####################################



